SELECT
	ORDER_DATE,
	NAME || ' (age:' || AGE || ')' AS PERSON_INFORMATION
FROM
	(
		SELECT
			ORDER_DATE,
			PERSON_ID AS ID
		FROM
			PERSON_ORDER
	)
	NATURAL JOIN PERSON
ORDER BY
	ORDER_DATE,
	PERSON_INFORMATION;