CREATE TABLE IF NOT EXISTS PERSON_DISCOUNTS (
	ID BIGINT NOT NULL PRIMARY KEY,
	PERSON_ID BIGINT NOT NULL,
	PIZZERIA_ID BIGINT NOT NULL,
	DISCOUNT NUMERIC NOT NULL DEFAULT 0,
	CONSTRAINT FK_PERSON_DISCOUNTS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
	CONSTRAINT FK_PERSON_DISCOUNTS_PIZZERIA_ID FOREIGN KEY (PIZZERIA_ID) REFERENCES PIZZERIA (ID)
);