SELECT
	PERSON.NAME,
	PIZZA_NAME,
	PRICE,
	ROUND(PRICE - (DISCOUNT * PRICE / 100)),
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM
	PERSON_ORDER
	JOIN PERSON ON PERSON_ORDER.PERSON_ID = PERSON.ID
	JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
	JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
	JOIN PERSON_DISCOUNTS ON PERSON_ORDER.PERSON_ID = PERSON_DISCOUNTS.PERSON_ID
	AND PERSON_DISCOUNTS.PIZZERIA_ID = MENU.PIZZERIA_ID
ORDER BY
	PERSON.NAME,
	PIZZA_NAME;