ALTER TABLE PERSON_DISCOUNTS
ADD CONSTRAINT CH_NN_PERSON_ID CHECK (PERSON_ID IS NOT NULL);

ALTER TABLE PERSON_DISCOUNTS
ADD CONSTRAINT CH_NN_PIZZERIA_ID CHECK (PIZZERIA_ID IS NOT NULL);

ALTER TABLE PERSON_DISCOUNTS
ADD CONSTRAINT CH_NN_DISCOUNT CHECK (DISCOUNT IS NOT NULL);

ALTER TABLE PERSON_DISCOUNTS
ALTER COLUMN DISCOUNT
SET DEFAULT 0;

ALTER TABLE PERSON_DISCOUNTS
ADD CONSTRAINT CH_RANGE_DISCOUNT CHECK (DISCOUNT BETWEEN 0 AND 100);