WITH
	TABLE_AMOUNT AS (
		SELECT
			PERSON_ID,
			PIZZERIA_ID,
			COUNT(PERSON_ID) AS AMOUNT
		FROM
			PERSON_ORDER
			JOIN MENU ON MENU_ID = MENU.ID
		GROUP BY
			PERSON_ID,
			PIZZERIA_ID
	)
INSERT INTO
	PERSON_DISCOUNTS (ID, PERSON_ID, PIZZERIA_ID, DISCOUNT)
SELECT
	ROW_NUMBER() OVER (),
	PERSON_ID,
	PIZZERIA_ID,
	CASE
		WHEN AMOUNT = 1 THEN 10.5
		WHEN AMOUNT = 2 THEN 22
		ELSE 30
	END
FROM
	TABLE_AMOUNT;