CREATE UNIQUE INDEX IF NOT EXISTS IDX_PERSON_DISCOUNTS_UNIQUE ON PERSON_DISCOUNTS (PERSON_ID, PIZZERIA_ID);

SET
	ENABLE_SEQSCAN = OFF;

EXPLAIN
ANALYZE
SELECT
	*
FROM
	PERSON_DISCOUNTS
WHERE
	PERSON_ID = 4
	AND PIZZERIA_ID = 9;