CREATE SEQUENCE IF NOT EXISTS SEQ_PERSON_DISCOUNTS AS BIGINT START
WITH
	1;

ALTER TABLE PERSON_DISCOUNTS
ALTER COLUMN ID
SET DEFAULT NEXTVAL('seq_person_discounts');

SELECT
	SETVAL(
		'seq_person_discounts',
		(
			SELECT
				MAX(ID)
			FROM
				PERSON_DISCOUNTS
		)
	);