SELECT
	PERSON.NAME AS NAME
FROM
	PERSON_ORDER
	JOIN PERSON ON PERSON.ID = PERSON_ID
	JOIN MENU ON MENU_ID = MENU.ID
WHERE
	GENDER = 'male'
	AND (
		PERSON.ADDRESS = 'Moscow'
		OR PERSON.ADDRESS = 'Samara'
	)
	AND (
		PIZZA_NAME = 'pepperoni pizza'
		OR PIZZA_NAME = 'mushroom pizza'
	)
ORDER BY
	PERSON.NAME DESC;