SELECT
	MENU.PIZZA_NAME AS PIZZA_NAME,
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM
	PERSON_ORDER
	JOIN PERSON ON PERSON.ID = PERSON_ID
	JOIN MENU ON MENU_ID = MENU.ID
	JOIN PIZZERIA ON PIZZERIA_ID = PIZZERIA.ID
WHERE
	PERSON.NAME = 'Denis'
	OR PERSON.NAME = 'Anna'
ORDER BY
	PIZZA_NAME,
	PIZZERIA_NAME;