SELECT
	COALESCE(PERSON.NAME, '-') AS PERSON_NAME,
	COALESCE(VISIT_DATE, NULL),
	COALESCE(PIZZERIA.NAME, '-') AS PIZZERIA_NAME
FROM
	(
		SELECT
			*
		FROM
			PERSON_VISITS
		WHERE
			VISIT_DATE BETWEEN '2022-01-01' AND '2022-01-03'
	)
	FULL JOIN PERSON ON PERSON_ID = PERSON.ID
	FULL JOIN PIZZERIA ON PIZZERIA.ID = PIZZERIA_ID
ORDER BY
	PERSON_NAME,
	VISIT_DATE,
	PIZZERIA_NAME;