SELECT
	PERSON_1.NAME AS PERSON_NAME1,
	PERSON_2.NAME AS PERSON_NAME2,
	PERSON_1.ADDRESS AS COMMON_ADDRESS
FROM
	PERSON PERSON_1
	JOIN PERSON PERSON_2 ON PERSON_1.ADDRESS = PERSON_2.ADDRESS
WHERE
	PERSON_1.ID > PERSON_2.ID
ORDER BY
	PERSON_NAME1,
	PERSON_NAME2,
	COMMON_ADDRESS;