SELECT
	PIZZA_NAME,
	PIZZERIA.NAME AS PIZZERIA_NAME,
	PRICE
FROM
	MENU
	LEFT JOIN PIZZERIA ON PIZZERIA_ID = PIZZERIA.ID
WHERE
	PIZZA_NAME = 'mushroom pizza'
	OR PIZZA_NAME = 'pepperoni pizza'
ORDER BY
	PIZZA_NAME,
	PIZZERIA_NAME;