WITH
	CTE AS (
		SELECT
			GENERATE_SERIES::DATE
		FROM
			GENERATE_SERIES('2022-01-01', '2022-01-10', '1 day'::INTERVAL)
	)
SELECT
	CTE AS MISSING_DATE
FROM
	CTE
	LEFT JOIN (
		SELECT
			VISIT_DATE
		FROM
			PERSON_VISITS
		WHERE
			PERSON_ID = 1
			OR PERSON_ID = 2
	) ON GENERATE_SERIES = VISIT_DATE
WHERE
	VISIT_DATE IS NULL
ORDER BY
	MISSING_DATE;