DROP MATERIALIZED VIEW IF EXISTS MV_DMITRIY_VISITS_AND_EATS;

DROP VIEW IF EXISTS V_PRICE_WITH_DISCOUNT;

DROP VIEW IF EXISTS V_SYMMETRIC_UNION;

DROP VIEW IF EXISTS V_GENERATED_DATES;

DROP VIEW IF EXISTS V_PERSONS_FEMALE;

DROP VIEW IF EXISTS V_PERSONS_MALE;