CREATE MATERIALIZED VIEW MV_DMITRIY_VISITS_AND_EATS AS (
	SELECT
		PIZZERIA.NAME AS PIZZERIA_NAME
	FROM
		PERSON_VISITS
		JOIN PERSON ON PERSON.ID = PERSON_ID
		JOIN MENU ON MENU.PIZZERIA_ID = PERSON_VISITS.PIZZERIA_ID
		JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
	WHERE
		VISIT_DATE = '2022-01-08'
		AND PERSON.NAME = 'Dmitriy'
		AND PRICE < 800
);