INSERT INTO
	PERSON_VISITS (ID, PERSON_ID, PIZZERIA_ID, VISIT_DATE)
VALUES
	(
		(
			SELECT
				MAX(ID) + 1
			FROM
				PERSON_VISITS
		),
		(
			SELECT
				ID
			FROM
				PERSON
			WHERE
				NAME = 'Dmitriy'
		),
		(
			SELECT
				PIZZERIA_ID
			FROM
				MENU
				JOIN PIZZERIA ON PIZZERIA_ID = PIZZERIA.ID
			WHERE
				PRICE < 800
				AND PIZZERIA.NAME != 'Papa Johns'
			LIMIT
				1
		),
		'2022-01-08'
	);

REFRESH MATERIALIZED VIEW MV_DMITRIY_VISITS_AND_EATS;