CREATE VIEW V_PRICE_WITH_DISCOUNT AS
SELECT
	PERSON.NAME,
	MENU.PIZZA_NAME,
	MENU.PRICE,
	CAST((PRICE - PRICE * 0.1) AS INT) AS DISCOUNT_PRICE
FROM
	PERSON_ORDER
	JOIN PERSON ON PERSON_ID = PERSON.ID
	JOIN MENU ON MENU_ID = MENU.ID
ORDER BY
	PERSON.NAME,
	MENU.PIZZA_NAME;