WITH
	WHO_VISIT_TABLE AS (
		SELECT
			PIZZERIA.NAME AS PIZZERIA_NAME,
			GENDER
		FROM
			PERSON_VISITS
			JOIN PERSON ON PERSON_ID = PERSON.ID
			JOIN PIZZERIA ON PIZZERIA_ID = PIZZERIA.ID
	)
SELECT
	PIZZERIA_NAME
FROM
	(
		(
			SELECT
				PIZZERIA_NAME
			FROM
				WHO_VISIT_TABLE
			WHERE
				GENDER = 'male'
			EXCEPT ALL
			SELECT
				PIZZERIA_NAME
			FROM
				WHO_VISIT_TABLE
			WHERE
				GENDER = 'female'
		)
		UNION ALL
		(
			SELECT
				PIZZERIA_NAME
			FROM
				WHO_VISIT_TABLE
			WHERE
				GENDER = 'female'
			EXCEPT ALL
			SELECT
				PIZZERIA_NAME
			FROM
				WHO_VISIT_TABLE
			WHERE
				GENDER = 'male'
		)
	)
ORDER BY
	PIZZERIA_NAME;