SELECT
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM
	PERSON_VISITS
	JOIN PERSON ON PERSON.ID = PERSON_VISITS.PERSON_ID
	JOIN PIZZERIA ON PIZZERIA.ID = PERSON_VISITS.PIZZERIA_ID
	LEFT JOIN PERSON_ORDER ON ORDER_DATE = VISIT_DATE
WHERE
	PERSON.NAME = 'Andrey'
	AND PERSON_ORDER.ID IS NULL
ORDER BY
	PIZZERIA_NAME;