WITH
	WORKPIECE AS (
		SELECT
			PIZZA_NAME,
			NAME,
			PRICE
		FROM
			PIZZERIA
			JOIN MENU ON PIZZERIA.ID = PIZZERIA_ID
	)
SELECT
	WORKPIECE_1.PIZZA_NAME,
	WORKPIECE_1.NAME AS PIZZERIA_NAME_1,
	WORKPIECE_2.NAME AS PIZZERIA_NAME_2,
	WORKPIECE_1.PRICE
FROM
	WORKPIECE AS WORKPIECE_1
	JOIN WORKPIECE AS WORKPIECE_2 ON WORKPIECE_1.PIZZA_NAME = WORKPIECE_2.PIZZA_NAME
WHERE
	WORKPIECE_1.PRICE = WORKPIECE_2.PRICE
	AND WORKPIECE_1.NAME < WORKPIECE_2.NAME
ORDER BY
	WORKPIECE_1.PIZZA_NAME;