SELECT
	PIZZA_NAME,
	PRICE,
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM
	MENU
	LEFT JOIN PERSON_ORDER ON MENU.ID = MENU_ID
	JOIN PIZZERIA ON PIZZERIA.ID = PIZZERIA_ID
WHERE
	MENU_ID IS NULL
ORDER BY
	PIZZA_NAME,
	PRICE;