SELECT
	PIZZA_NAME,
	PRICE,
	PIZZERIA.NAME AS PIZZERIA_NAME,
	VISIT_DATE
FROM
	PERSON_VISITS
	JOIN MENU ON PERSON_VISITS.PIZZERIA_ID = MENU.PIZZERIA_ID
	JOIN PERSON ON PERSON_VISITS.PERSON_ID = PERSON.ID
	JOIN PIZZERIA ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
WHERE
	PERSON.NAME = 'Kate'
	AND PRICE BETWEEN 800 AND 1000
ORDER BY
	PIZZA_NAME,
	PRICE,
	PIZZERIA_NAME;