SELECT
	ACTION_DATE,
	NAME AS PERSON_NAME
FROM
	(
		SELECT
			ORDER_DATE AS ACTION_DATE,
			PERSON_ID AS PERSON_ID
		FROM
			PERSON_ORDER
		INTERSECT
		SELECT
			VISIT_DATE,
			PERSON_ID
		FROM
			PERSON_VISITS
	)
	JOIN PERSON ON ID = PERSON_ID
ORDER BY
	ACTION_DATE,
	PERSON_NAME DESC;