WITH
	CTE_VOLUME AS (
		SELECT
			USER_ID,
			CURRENCY_ID,
			TYPE,
			SUM(MONEY) AS VOLUME
		FROM
			BALANCE
		GROUP BY
			USER_ID,
			CURRENCY_ID,
			TYPE
	),
	CTE_LAST_RATE_USD AS (
		SELECT DISTINCT ON (ID) 
			ID,
			NAME,
			RATE_TO_USD AS LAST_RATE,
			UPDATED
		FROM
			CURRENCY
		ORDER BY
			ID,
			UPDATED DESC
	)
SELECT
	COALESCE(CLIENT.NAME, 'not defined') AS NAME,
	COALESCE(CLIENT.LASTNAME, 'not defined') AS LASTNAME,
	CTE_VOLUME.TYPE AS TYPE,
	CTE_VOLUME.VOLUME AS VOLUME,
	COALESCE(CTE_LAST_RATE_USD.NAME, 'not defined') AS CURRENCY_NAME,
	COALESCE(CTE_LAST_RATE_USD.LAST_RATE, 1) AS LAST_RATE_TO_USD,
	VOLUME * COALESCE(CTE_LAST_RATE_USD.LAST_RATE, 1) AS TOTAL_VOLUME_IN_USD
FROM
	CTE_VOLUME
	LEFT JOIN "user" AS CLIENT ON CTE_VOLUME.USER_ID = CLIENT.ID
	LEFT JOIN CTE_LAST_RATE_USD ON CTE_VOLUME.CURRENCY_ID = CTE_LAST_RATE_USD.ID
ORDER BY
	NAME DESC,
	LASTNAME,
	TYPE;