WITH RECURSIVE
	RECURSIVE_QUERY AS (
		SELECT
			NODE_1 AS CURRENT,
			CAST('{' || NODE_1 AS VARCHAR) AS PATHS,
			0 AS TOTAL_COST,
			1 AS STEPS
		FROM
			NODES
		WHERE
			NODE_1 = 'a'
		UNION
		SELECT
			NODES.NODE_2 AS CURRENT,
			RECURSIVE_QUERY.PATHS || ',' || NODES.NODE_2,
			RECURSIVE_QUERY.TOTAL_COST + NODES.COST,
			RECURSIVE_QUERY.STEPS + 1
		FROM
			RECURSIVE_QUERY
			JOIN NODES ON RECURSIVE_QUERY.CURRENT = NODES.NODE_1
		WHERE
			RECURSIVE_QUERY.PATHS NOT LIKE '%' || NODES.NODE_2 || '%'
	),
	FINAL_TOUR AS (
		SELECT
			RECURSIVE_QUERY.TOTAL_COST + NODES.COST AS TOTAL_COST,
			RECURSIVE_QUERY.PATHS || ',' || NODES.NODE_2 || '}' AS TOUR
		FROM
			RECURSIVE_QUERY
			JOIN NODES ON RECURSIVE_QUERY.CURRENT = NODES.NODE_1
			AND NODES.NODE_2 = 'a'
		WHERE
			RECURSIVE_QUERY.STEPS = (
				SELECT
					COUNT(DISTINCT NODE_1)
				FROM
					NODES
			)
		ORDER BY
			TOTAL_COST,
			TOUR
	)
SELECT
	*
FROM
	FINAL_TOUR;