CREATE INDEX IF NOT EXISTS IDX_PERSON_ORDER_MULTI ON PERSON_ORDER (PERSON_ID, MENU_ID, ORDER_DATE);

SET
	ENABLE_SEQSCAN TO OFF;

EXPLAIN
ANALYZE
SELECT
	PERSON_ID,
	MENU_ID,
	ORDER_DATE
FROM
	PERSON_ORDER
WHERE
	PERSON_ID = 8
	AND MENU_ID = 19;