CREATE UNIQUE INDEX IF NOT EXISTS IDX_MENU_UNIQUE ON MENU (PIZZERIA_ID, PIZZA_NAME);

SET
	ENABLE_SEQSCAN TO OFF;

EXPLAIN
ANALYZE
SELECT
	PIZZERIA_ID,
	PIZZA_NAME
FROM
	MENU
WHERE
	PIZZERIA_ID = 1
	AND PIZZA_NAME = 'cheese pizza';