SELECT
	ORDER_DATE,
	NAME || ' (age:' || AGE || ')' AS PERSON_INFORMATION
FROM
	(
		SELECT
			ORDER_DATE,
			PERSON_ID
		FROM
			PERSON_ORDER
	)
	JOIN PERSON ON ID = PERSON_ID
ORDER BY
	ORDER_DATE,
	PERSON_INFORMATION;