CREATE TABLE IF NOT EXISTS PERSON_AUDIT (
	CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	TYPE_EVENT CHAR(1) DEFAULT 'I' NOT NULL CONSTRAINT CH_TYPE_EVENT CHECK (TYPE_EVENT IN ('I', 'U', 'D')),
	ROW_ID BIGINT NOT NULL,
	NAME VARCHAR,
	AGE INTEGER,
	GENDER VARCHAR,
	ADDRESS VARCHAR
);

CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_INSERT_AUDIT () RETURNS TRIGGER AS $FNC_TRG_PERSON_INSERT_AUDIT$
BEGIN
    INSERT INTO PERSON_AUDIT(ROW_ID, NAME, AGE, GENDER, ADDRESS)
    VALUES (NEW.ID, NEW.NAME, NEW.AGE, NEW.GENDER, NEW.ADDRESS);
    RETURN NEW;
END;
$FNC_TRG_PERSON_INSERT_AUDIT$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER TRG_PERSON_INSERT_AUDIT
AFTER INSERT ON PERSON FOR EACH ROW
EXECUTE FUNCTION FNC_TRG_PERSON_INSERT_AUDIT ();

INSERT INTO
	PERSON (ID, NAME, AGE, GENDER, ADDRESS)
VALUES
	(10, 'Damir', 22, 'male', 'Irkutsk');

SELECT
	*
FROM
	PERSON_AUDIT;