CREATE OR REPLACE FUNCTION FNC_FIBONACCI (PSTOP INT DEFAULT 10) RETURNS SETOF INTEGER AS $FNC_FIBONACCI$
        WITH RECURSIVE CTE_FIBONACCI(CURRENT_NUMBER, NEXT_NUMBER) AS (
            VALUES (0, 1)
        UNION
            SELECT NEXT_NUMBER, CURRENT_NUMBER + NEXT_NUMBER FROM CTE_FIBONACCI
            WHERE NEXT_NUMBER < PSTOP)
        SELECT CURRENT_NUMBER FROM CTE_FIBONACCI;
    $FNC_FIBONACCI$ LANGUAGE SQL;

SELECT
	*
FROM
	FNC_FIBONACCI (100);

SELECT
	*
FROM
	FNC_FIBONACCI ();