DROP FUNCTION IF EXISTS FNC_PERSONS_FEMALE ();
DROP FUNCTION IF EXISTS FNC_PERSONS_MALE ();

CREATE OR REPLACE FUNCTION FNC_PERSONS (IN PGENDER VARCHAR DEFAULT 'female') RETURNS TABLE (
	ID BIGINT,
	NAME VARCHAR,
	AGE INTEGER,
	GENDER VARCHAR,
	ADDRESS VARCHAR
) AS $$
        SELECT *
        FROM PERSON
        WHERE GENDER = PGENDER;
    $$ LANGUAGE SQL;

SELECT
	*
FROM
	FNC_PERSONS (PGENDER := 'male');

SELECT
	*
FROM
	FNC_PERSONS ();