/*PERSON_AUDIT(CREATED, TYPE_EVENT, ROW_ID, NAME, AGE, GENDER, ADDRESS)*/

CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_DELETE_AUDIT () RETURNS TRIGGER AS $FNC_TRG_PERSON_DELETE_AUDIT$
BEGIN
    INSERT INTO PERSON_AUDIT(TYPE_EVENT, ROW_ID, NAME, AGE, GENDER, ADDRESS)
    VALUES ('D', OLD.ID, OLD.NAME, OLD.AGE, OLD.GENDER, OLD.ADDRESS);
    RETURN OLD;
END;
$FNC_TRG_PERSON_DELETE_AUDIT$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER TRG_PERSON_DELETE_AUDIT
AFTER DELETE ON PERSON FOR EACH ROW
EXECUTE FUNCTION FNC_TRG_PERSON_DELETE_AUDIT ();

DELETE FROM PERSON
WHERE
	ID = 10;

SELECT
	*
FROM
	PERSON_AUDIT;