--DROP FUNCTION IF EXISTS FNC_PERSON_VISITS_AND_EATS_ON_DATE ();
CREATE OR REPLACE FUNCTION FNC_PERSON_VISITS_AND_EATS_ON_DATE (
	IN PPERSON VARCHAR DEFAULT 'Dmitriy',
	IN PPRICE NUMERIC DEFAULT 500,
	IN PDATE DATE DEFAULT '2022-01-08'
) RETURNS TABLE (NAME VARCHAR) AS $FNC_PERSON_VISITS_AND_EATS_ON_DATE$
        BEGIN
            RETURN QUERY
               (
					SELECT
						PIZZERIA.NAME
					FROM
						PERSON_VISITS
						JOIN PERSON ON PERSON_VISITS.PERSON_ID = PERSON.ID
						JOIN PIZZERIA ON PIZZERIA.ID = PERSON_VISITS.PIZZERIA_ID
					WHERE
						PERSON_VISITS.VISIT_DATE = PDATE
						AND PERSON.NAME = PPERSON
				)
				INTERSECT
				(
					SELECT
						PIZZERIA.NAME
					FROM
						MENU
						JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
					WHERE
						MENU.PRICE < PPRICE
				);
        END;
    $FNC_PERSON_VISITS_AND_EATS_ON_DATE$ LANGUAGE PLPGSQL;

SELECT
	*
FROM
	FNC_PERSON_VISITS_AND_EATS_ON_DATE (PPRICE := 800);

SELECT
	*
FROM
	FNC_PERSON_VISITS_AND_EATS_ON_DATE (
		PPERSON := 'Anna',
		PPRICE := 1300,
		PDATE := '2022-01-01'
	);