CREATE OR REPLACE FUNCTION FNC_PERSONS_FEMALE () RETURNS TABLE (
	ID BIGINT,
	NAME VARCHAR,
	AGE INTEGER,
	GENDER VARCHAR,
	ADDRESS VARCHAR
) AS $FNC_PERSONS_FEMALE$
        SELECT * FROM PERSON
        WHERE GENDER = 'female';
    $FNC_PERSONS_FEMALE$ LANGUAGE SQL;

CREATE OR REPLACE FUNCTION FNC_PERSONS_MALE () RETURNS TABLE (
	ID BIGINT,
	NAME VARCHAR,
	AGE INTEGER,
	GENDER VARCHAR,
	ADDRESS VARCHAR
) AS $FNC_PERSONS_MALE$
        SELECT * FROM PERSON
        WHERE GENDER = 'male';
    $FNC_PERSONS_MALE$ LANGUAGE SQL;

SELECT
	*
FROM
	FNC_PERSONS_MALE ();

SELECT
	*
FROM
	FNC_PERSONS_FEMALE ();