/*PERSON_AUDIT(CREATED, TYPE_EVENT, ROW_ID, NAME, AGE, GENDER, ADDRESS)*/

CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_UPDATE_AUDIT () RETURNS TRIGGER AS $FNC_TRG_PERSON_UPDATE_AUDIT$
BEGIN
    INSERT INTO PERSON_AUDIT(TYPE_EVENT, ROW_ID, NAME, AGE, GENDER, ADDRESS)
    VALUES ('U', OLD.ID, OLD.NAME, OLD.AGE, OLD.GENDER, OLD.ADDRESS);
    RETURN OLD;
END;
$FNC_TRG_PERSON_UPDATE_AUDIT$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER TRG_PERSON_UPDATE_AUDIT
AFTER UPDATE ON PERSON FOR EACH ROW
EXECUTE FUNCTION FNC_TRG_PERSON_UPDATE_AUDIT ();

UPDATE PERSON
SET
	NAME = 'Bulat'
WHERE
	ID = 10;

UPDATE PERSON
SET
	NAME = 'Damir'
WHERE
	ID = 10;

SELECT
	*
FROM
	PERSON_AUDIT;