CREATE OR REPLACE FUNCTION FUNC_MINIMUM (VARIADIC ARR NUMERIC[]) RETURNS NUMERIC AS $FUNC_MINIMUM$
    SELECT MIN(UNNEST) FROM UNNEST(ARR);
$FUNC_MINIMUM$ LANGUAGE SQL;

SELECT
	FUNC_MINIMUM (VARIADIC ARR => ARRAY[10.0, -1.0, 5.0, 4.4]);