SELECT
	NAME,
	COUNT(PIZZERIA_ID) AS COUNT_OF_ORDERS,
	ROUND(AVG(PRICE),2) AS AVERAGE_PRICE,
	MAX(PRICE) AS MAX_PRICE,
	MIN(PRICE) AS MIN_PRICE
FROM
	PERSON_ORDER
	JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
	JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
GROUP BY
	NAME
ORDER BY
	NAME