WITH
	CTE_FORMULA AS (
		SELECT
			ADDRESS,
			ROUND(
				(
					MAX(AGE) - ((CAST(MIN(AGE) AS DECIMAL(10, 2)) / MAX(AGE)))
				),
				2
			) AS FORMULA,
			ROUND(AVG(AGE), 2) AS AVERAGE
		FROM
			PERSON
		GROUP BY
			ADDRESS
	)
SELECT
	*,
	CASE
		WHEN FORMULA > AVERAGE THEN TRUE
		ELSE FALSE
	END AS COMPARISON
FROM
	CTE_FORMULA
ORDER BY
	ADDRESS;