SELECT
	NAME,
	SUM(COUNT) AS TOTAL_COUNT
FROM
	(
		(
			SELECT
				NAME,
				COUNT(PIZZERIA_ID) AS COUNT
			FROM
				PERSON_VISITS
				JOIN PIZZERIA ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
			GROUP BY
				NAME
		)
		UNION ALL
		(
			SELECT
				NAME,
				COUNT(PIZZERIA_ID)
			FROM
				PERSON_ORDER
				JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
				JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
			GROUP BY
				NAME
		)
	)
GROUP BY
	NAME
ORDER BY
	TOTAL_COUNT DESC,
	NAME;