SELECT
	ADDRESS,
	PIZZERIA.NAME,
	COUNT(PERSON_ID) AS count_of_orders
FROM
	PERSON_ORDER
	JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
	JOIN PERSON ON PERSON_ORDER.PERSON_ID = PERSON.ID
	JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
GROUP BY
	ADDRESS,
	PIZZERIA.NAME
ORDER BY
	ADDRESS,
	PIZZERIA.NAME;