(
	SELECT
		NAME,
		COUNT(PIZZERIA_ID) AS COUNT,
		'visit' AS ACTION_TYPE
	FROM
		PERSON_VISITS
		JOIN PIZZERIA ON PERSON_VISITS.PIZZERIA_ID = PIZZERIA.ID
	GROUP BY
		NAME
	ORDER BY
		COUNT DESC,
		NAME
	LIMIT
		3
)
UNION ALL
(
	SELECT
		NAME,
		COUNT(PIZZERIA_ID) ,
		'order' 
	FROM
		PERSON_ORDER
		JOIN MENU ON PERSON_ORDER.MENU_ID = MENU.ID
		JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
	GROUP BY
		NAME
	ORDER BY
		COUNT DESC,
		NAME
	LIMIT
		3
)
ORDER BY
	ACTION_TYPE,
	COUNT DESC;