SELECT
	PERSON.NAME AS PERSON_NAME,
	MENU.PIZZA_NAME,
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM
	PERSON_ORDER
	JOIN PERSON ON PERSON.ID = PERSON_ID
	JOIN MENU ON MENU.ID = MENU_ID
	JOIN PIZZERIA ON PIZZERIA.ID = MENU.PIZZERIA_ID
ORDER BY
	PERSON_NAME,
	PIZZA_NAME,
	PIZZERIA_NAME;